language: python

python:
  - 3.5.1

cache:
  pip: true
  directories:
  - "$HOME/.pip-cache/"
  - "$HOME/virtualenv/python3.5.1"

install:
  - pip install coveralls
  - pip install -r etc/requirements.txt --download-cache $HOME/.pip-cache

script:
  - coverage run setup.py test

after_success:
  - coveralls
