language: python

python:
  - 3.5.1

install:
  - pip install coveralls

cache:
  pip: true
  directories:
  - "$HOME/.pip-cache/"
  - "$HOME/virtualenv/python3.5.1"

script:
  - coverage run setup.py test